application: statesofmind-dev
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest